[package]
name = "warp-rg-libp2p"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
warp = { path = "../../warp" }

#libp2p = { git = "https://github.com/libp2p/rust-libp2p", features = ["tcp-tokio"] } # TODO: Lock to a specific commit until version is publish

[features]
default = []