[package]
name = "warp-tesseract"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
warp-common = { version = "0.1.0", path = "../warp-common" }
warp-crypto = { version = "0.1.0", path = "../warp-crypto" }

[features]
default = ["async", "indirect"]
async = ["warp-common/async"]
direct = []
indirect = []