[workspace]
members = [
  "config/warp-configuration",
  "modules/warp-constellation",
  "modules/warp-pocket-dimension",
  "modules/warp-multipass",
  "modules/warp-raygun",
  "extensions/warp-pd-stretto",
  "extensions/warp-pd-flatfile",
  "misc/warp-tui",
  "utils/warp-hooks",
  "utils/warp-common",
  "utils/warp-data",
  "utils/warp-module",
  "warp",
]
