[workspace]
members = [
  "config/warp-configuration",
  "modules/warp-constellation",
  "modules/warp-pocket-dimension",
  "modules/warp-multipass",
  "modules/warp-raygun",
  "utils/warp-hooks",
  "utils/warp-data",
  "warp",
]
