[workspace]
members = [
  "config/warp-configuration",
  "modules/warp-constellation",
  "modules/warp-pocket-dimension",
  "modules/warp-multipass",
  "modules/warp-raygun",
  "extensions/warp-pd-stretto",
  "extensions/warp-pd-flatfile",
  "extensions/warp-fs-memory",
  "extensions/warp-fs-textile",
  "extensions/warp-fs-ipfs",
  "extensions/warp-fs-storj",
  "extensions/warp-rg-ipfs",
  "extensions/warp-rg-textile",
  "extensions/warp-mp-solana",
  "extensions/warp-rg-libp2p",
  "misc/warp-tui",
  "utils/warp-hooks",
  "utils/warp-common",
  "utils/warp-data",
  "utils/warp-module",
  "utils/warp-tesseract",
  "utils/warp-install",
  "utils/warp-solana-utils",
  "warp",
]
