[package]
name = "warp-crypto"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib", "staticlib"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
x25519-dalek = { version = "1" }
ed25519-dalek = { version = "1" }
curve25519-dalek = "3.2"
rsa = { version = "0.5" }
chacha20poly1305 = { version = "0.9", features = ["stream"] }
blake2 = { version = "0.10"  }
sha1   = { version = "0.10" }
sha2   = { version = "0.10"  }
sha3   = { version = "0.10"  }
digest = { version = "0.10" }
aes-gcm = { version = "0.9" }
aead = { version = "0.4", default-features = false }
anyhow = { version = "1" }
zeroize = "1"
cfg-if = "1.0"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
rand = { version = "0.7"  }
getrandom = { version = "0.2" }

[target.'cfg(target_arch = "wasm32")'.dependencies]
getrandom = { version = "0.2", features = ["js"] }
wasm-bindgen = { version = "0.2" }
web-sys = { version = "0.3" }
js-sys = { version = "0.3" }

[target.'cfg(not(target_arch = "wasm32"))'.dev-dependencies]
hex = "0.4"

[features]
default = []