debug = true

[http_api]
enabled = false

[modules]
pocket_dimension = true
constellation = true
multipass = false
raygun = false

[extensions]
constellation = ["warp-fs-storj", "warp-fs-memory"]
pocket_dimension = ["warp-pd-stretto"]
raygun = []
multipass = []
