[package]
name = "warp-common"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
thiserror = "1.0"

serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0.78" }
serde_yaml = "0.8"
toml = "0.5"
chrono = { version = "0.4", features = ["serde"] }
regex = "1"
futures = { version = "0.3", optional = true }
async-trait = { version = "0.1", optional = true }
warp-module = { version = "0.1.0", path = "../warp-module" }
cfg-if = "1.0"
libflate = "1"
log = "0.4"
derive_more = "0.99"
hex = "0.4"
bs58 = "0.4.0"

tiny-bip39 = "0.8"

[target.'cfg(not(all(target_arch = "wasm32", not(any(target_os = "emscripten", target_os = "wasi", target_os="android")))))'.dependencies]
dirs = "4.0"

[target.'cfg(not(all(target_arch = "wasm32", not(any(target_os = "emscripten", target_os = "wasi")))))'.dependencies]
uuid = { version = "0.8", features = ["serde", "v4"] }
tokio = { version = "1", features = ["full"], optional = true }
tokio-util = { version = "0.6", features = ["full"], optional = true }
tokio-stream = { version = "0.1", features = ["net"], optional = true }


[target.'cfg(all(target_arch = "wasm32", not(any(target_os = "emscripten", target_os = "wasi"))))'.dependencies]
getrandom = { version = "0.2", features = ["js"] }
uuid = { version = "0.8", features = ["serde", "v4", "wasm-bindgen"] }
wasm-bindgen = { version = "0.2" }
web-sys = { version = "0.3" }
js-sys = { version = "0.3" }

[features]
default = []
async = ["tokio", "tokio-util", "async-trait", "futures", "tokio-stream"]