[package]
name = "warp-common"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
thiserror = "1.0"

serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0.78" }
chrono = { version = "0.4", features = ["serde"] }
regex = "1.5.4"
futures = { version = "0.3", optional = true }

[target.'cfg(not(all(target_arch = "wasm32", not(any(target_os = "emscripten", target_os = "wasi")))))'.dependencies]
uuid = { version = "0.8", features = ["serde", "v4"] }
tokio = { version = "1", features = ["full"], optional = true }
tokio-util = { version = "0.6", features = ["full"], optional = true }
async-trait = { version = "0.1", optional = true }
bincode = "1.3.3"

[target.'cfg(all(target_arch = "wasm32", not(any(target_os = "emscripten", target_os = "wasi"))))'.dependencies]
getrandom = { version = "0.2", features = ["js"] }
uuid = { version = "0.8", features = ["serde", "v4", "wasm-bindgen"] }
wasm-bindgen = "0.2"
web-sys = "0.3"
js-sys = "0.3"