[package]
name = "warp-rg-ipfs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#warp-common 	= { path = "../../utils/warp-common", features = ["async"]}
#warp-raygun 	= { path = "../../modules/warp-raygun" }
#warp-multipass 	= { path = "../../modules/warp-multipass" }
#warp-module 	= { path = "../../utils/warp-module" }
#warp-crypto 	= { path = "../../utils/warp-crypto" }

ipfs-api-backend-hyper    = { version = "0.4", features = ["with-send-sync", "with-hyper-tls"], optional = true}
hyper-tls 				  = { version = "0.5", optional = true }
hyper                     = { version = "0.14", features = ["http1", "http2", "client", "tcp"], optional = true }
http 					  = { version = "0.2", optional = true }
ipfs 					  = { git = "https://github.com/rs-ipfs/rust-ipfs", optional = true}

[features]
default = []
http_api = ["ipfs-api-backend-hyper", "hyper-tls", "hyper", "http"]
native = ["ipfs"]