[package]
name = "warp-hooks"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
warp-module = { version = "0.1.0", path = "../warp-module" }
warp-data = { version = "0.1.0", path = "../warp-data" }
warp-common = { version = "0.1.0", path = "../warp-common" }

[dev-dependencies]
warp-constellation = { version = "0.1.0", path = "../../modules/warp-constellation" }