[package]
name = "warp-fs-ipfs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ipfs-api-backend-hyper    = { version = "0.4", features = ["with-send-sync", "with-hyper-tls"] }
hyper-tls = "0.5"
hyper                     = { version = "0.14", features = ["http1", "http2", "client", "tcp"] }
http = "0.2"

warp-constellation = { path = "../../modules/warp-constellation" }
warp-pocket-dimension = { path = "../../modules/warp-pocket-dimension" }
warp-module = { path = "../../utils/warp-module" }
warp-data = { path = "../../utils/warp-data" }
warp-hooks = { path = "../../utils/warp-hooks" }
warp-common = { path = "../../utils/warp-common", features = ["async", "use_sha1", "use_sha2"]}