[package]
name = "warp"
version = "0.1.0"
description = "TBD"
# readme = "README.md"
license = "MIT"
edition = "2021"
repository = "https://github.com/Satellite-im/Warp"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
uuid = { version = "0.8", features = ["serde", "v4"] }

warp-constellation = { path = "../modules/warp-constellation" }
warp-pocket-dimension = { path = "../modules/warp-pocket-dimension" }
warp-multipass = { path = "../modules/warp-multipass" }
warp-raygun = { path = "../modules/warp-raygun" }
warp-hooks = { path = "../utils/warp-hooks" }
warp-module = { path = "../utils/warp-module" }
warp-data = { path = "../utils/warp-data" }
warp-common = { path = "../utils/warp-common" }
warp-pd-stretto = { path = "../extensions/warp-pd-stretto" }