[package]
name = "warp-fs-memory"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib", "staticlib"]

[dependencies]
warp = { path = "../../warp" }

tokio = { version = "1", features = ["full"] }
async-trait = "0.1"

anyhow = "1"

serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0" }
chrono = { version = "0.4", features = ["serde"] }

thiserror = "1.0"
dyn-clone = "1.0"
uuid = { version = "0.8", features = ["serde", "v4"] }