[package]
name = "warp-fs-memory"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib", "staticlib"]

[dependencies]
warp-constellation = { path = "../../modules/warp-constellation" }
warp-pocket-dimension = { path = "../../modules/warp-pocket-dimension" }
warp-hooks = { path = "../../utils/warp-hooks" }
warp-module = { path = "../../utils/warp-module" }
warp-data = { path = "../../utils/warp-data" }
warp-common = { path = "../../utils/warp-common", features = ["async"]}

thiserror = "1.0"
dyn-clone = "1.0"