[package]
name = "warp-data"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0"
warp-module = { version = "0.1.0", path = "../warp-module" }
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0.78" }
uuid = { version = "0.8", features = ["serde", "v4"] }
chrono = { version = "0.4", features = ["serde"] }