name: Build Android Libraries
on: [push]

jobs:
  build_android_libraries:
    name: Building Libraries
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        target: [aarch64-linux-android, armv7-linux-androideabi, i686-linux-android, x86_64-linux-android]
        include:
          - target: aarch64-linux-android
            platform: android
            os: ubuntu-latest
          - target: armv7-linux-androideabi
            platform: android
            os: ubuntu-latest
          - target: i686-linux-android
            platform: android
            os: ubuntu-latest
          - target: x86_64-linux-android
            platform: android
            os: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r22b
          add-to-path: false
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
      - name: Install cargo-ndk
        if: ${{ matrix.platform == 'android' }}
        run: cargo install cargo-ndk
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y llvm-dev cmake libudev-dev
      - uses: actions-rs/cargo@v1
        if: ${{ matrix.platform == 'android' }}
        with:
          command: ndk
          args: --target ${{ matrix.target }} -p 29 -o ./jniLibs build -p warp -p warp-mp-ipfs
        env:
          ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}