name: Wasm-Pack build
on: ["push"]
  # push:
  #   paths:
  #     - 'extensions/warp-ipfs/**'
  # pull_request:
  #   paths: 
  #     - 'extensions/warp-ipfs/**'

jobs:
  push_wasm_pack:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v4
      - name: Push wasm-pack to remote
        id: wasm-pack
        uses: ./.github/actions/wasm-pack
      - name: Push Remote
        run: |
          ls .
          cd extensions/warp-ipfs
          ls .
