[package]
name = "warp-solana-utils"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
warp-common = { path = "../../utils/warp-common", features = ["async"] }
warp-crypto = { path = "../../utils/warp-crypto" }
users = { git = "https://github.com/Satellite-im/solana-programs", features = ["no-entrypoint"] }
friends = { git = "https://github.com/Satellite-im/solana-programs", features = ["no-entrypoint"] }
groupchats = { git = "https://github.com/Satellite-im/solana-programs", features = ["no-entrypoint"] }
anchor-client = "0.20"
bincode = "1.3.3"
borsh = "0.9"
bs58 = "0.4.0"
# TODO: Remove blocking feature and use async in the future
reqwest = { version = "0.11", features = ["blocking", "json"] }