[package]
name = "warp-solana-utils"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
warp-common = { path = "../../utils/warp-common", features = ["async", "use_sha2", "use_solana"] }
bincode = "1.3.3"