[package]
name = "warp-solana-utils"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
warp-common = { path = "../../utils/warp-common", features = ["async"] }
warp-crypto = { path = "../../utils/warp-crypto" }
users = { git = "https://github.com/Satellite-im/solana-programs" }
friends = { git = "https://github.com/Satellite-im/solana-programs" }
anchor-client = "0.20"
bincode = "1.3.3"
borsh = "0.9"
bs58 = "0.4.0"