[package]
name = "warp-solana-utils"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
warp-common = { path = "../../utils/warp-common" }
warp-crypto = { path = "../../utils/warp-crypto" }
users = { git = "https://github.com/Satellite-im/solana-programs", features = ["no-entrypoint"], rev = "139e02a0060f7ba94e998abb4d64451d2de61ad0"}
friends = { git = "https://github.com/Satellite-im/solana-programs", features = ["no-entrypoint"], rev = "139e02a0060f7ba94e998abb4d64451d2de61ad0" }
groupchats = { git = "https://github.com/Satellite-im/solana-programs", features = ["no-entrypoint"], rev = "139e02a0060f7ba94e998abb4d64451d2de61ad0" }
anchor-client = "0.24.2"

# TODO: Remove blocking feature and use async in the future
reqwest = { version = "0.11", features = ["blocking", "json"] }